In [9]:
import sklearn
import sklearn.datasets
import sklearn.tree
import matplotlib.pyplot as plt
import sklearn.linear_model
import pandas as pd
import numpy as np
import sklearn.ensemble
import pylab as pl

In [10]:
import pickle 
import scipy.misc as smp

In [11]:
import os

In [12]:
import sklearn.naive_bayes

In [4]:
root_dir =("/Users/hardiktaneja/Downloads/DevanagariHandwrittenCharacterDataset/Train/character_1_ka")

In [11]:
len(os.listdir(root_dir))

1700

In [9]:
os.path.join(root_dir,os.listdir(root_dir)[0])

'/Users/hardiktaneja/Downloads/DevanagariHandwrittenCharacterDataset/Train/character_1_ka/10962.png'

In [15]:
file_paths = [os.path.join(root_dir,f) for f in os.listdir(root_dir)]

In [12]:
len(file_paths)

1700

In [18]:
from PIL import Image
img = Image.open('/Users/hardiktaneja/Downloads/DevanagariHandwrittenCharacterDataset/Train/character_1_ka/10962.png')

In [44]:
img =np.asarray(img)
img.shape

(32, 32)

In [45]:
img

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,  49, ..., 143,   0,   0],
       ..., 
       [  0,   0,  28, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)

In [37]:
import imageio

im = imageio.imread('/Users/hardiktaneja/Downloads/DevanagariHandwrittenCharacterDataset/Train/character_1_ka/10962.png')
print(im.shape)

(32, 32)


In [ ]:
root_dir =
filepaths = [os.path.join(root_dir,f) for f in os.listdir(root_dir)]

In [60]:
root_dir = '/Users/hardiktaneja/Downloads/DevanagariHandwrittenCharacterDataset/Train'
filepaths1 = [os.path.join(root_dir,f) for f in os.listdir(root_dir)]

In [102]:
filepaths1[1].split('/')[len(filepaths1[1].split('/'))-1].split('_')[1]

'10'

In [101]:
imgarr=[]
targetarr=[]
for j in filepaths1:
    root_dir = j
#     if(j == "/Users/hardiktaneja/Downloads/DevanagariHandwrittenCharacterDataset/Train/digit_0"):
#         break
    if(j == '/Users/hardiktaneja/Downloads/DevanagariHandwrittenCharacterDataset/Train/.DS_Store'):
        continue
    filepaths = [os.path.join(root_dir,f) for f in os.listdir(root_dir)]
    for i in filepaths:
        img = Image.open(i)
        h = np.array(img)
        imgarr.append(h)
        m =int(j.split('/')[len(j.split('/'))-1].split('_')[1])
        targetarr.append(m)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/hardiktaneja/Downloads/DevanagariHandwrittenCharacterDataset/Train/digit_0'

In [91]:
len(imgarr)

61200

In [81]:
len(targetarr)

78200

In [99]:
targetarr[61200-1]

9

In [82]:
imgarr[0]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [46]:
(imgarr[0]).reshape(1024)[986]

0

In [92]:
x = np.array(imgarr,float).reshape(61200,1024)
y = np.array(targetarr)

In [93]:
print(x.shape)
print(y.shape)

(61200, 1024)
(61200,)


In [94]:
x_train,x_test,y_train,y_test = sklearn.model_selection.train_test_split(x,y,test_size=.2)

In [95]:
x_train.shape

(48960, 1024)

In [50]:
y

array([ 1,  1,  1, ..., 46, 46, 46])

In [96]:
clf = sklearn.ensemble.RandomForestClassifier(random_state=0)
clf.fit(x,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [97]:
clf.score(x,y)

0.027777777777777776

In [39]:
model = sklearn.naive_bayes.GaussianNB()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.010549872122762148

In [ ]:
model = sklearn.svm.SVC()
model.fit(x_train,y_train)
model.score(x_test,y_test)